"""empty message

Revision ID: 2b58f842c334
Revises: 7616f97ecfab
Create Date: 2025-03-01 01:12:26.276523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b58f842c334'
down_revision = '7616f97ecfab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('population', sa.String(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('gas', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_favorite', sa.Integer(), nullable=False),
    sa.Column('planet_favorite', sa.Integer(), nullable=False),
    sa.Column('people_favorite', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['people_favorite'], ['people.id'], ),
    sa.ForeignKeyConstraint(['planet_favorite'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['user_favorite'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    op.drop_table('planet')
    # ### end Alembic commands ###
